# Note: Running a DNS server like Unbound requires careful network configuration.
# Consider if you really need this or if your router/ISP DNS is sufficient.
version: "3.8"
services:
  unbound:
    image: mvance/unbound:latest
    container_name: unbound
    environment:
      - PUID=2000 # Check image docs if these are used
      - PGID=2000
      - TZ=America/New_York
    ports:
      - "53:53/tcp" # Standard DNS ports
      - "53:53/udp"
    volumes:
      - /opt/podman-data/unbound/config:/opt/unbound/etc/unbound/ # Mount config dir
    cap_add: # May need NET_BIND_SERVICE to bind to low port 53 as non-root
      - NET_BIND_SERVICE
    restart: unless-stopped
    networks:
      # Unbound usually provides DNS, doesn't rely on other services heavily
      # Might attach to media_network if other containers need to resolve *.localhost domains served by it
      - media_network

networks:
  media_network:
    external: true
    name: media_network
