version: "3.8"
services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - PUID=2000
      - PGID=2000
      - TZ=America/New_York
      - LOG_LEVEL=info
    volumes:
      - /opt/podman-data/jellyseerr/config:/app/config
    ports:
      # - "5055:5055" # Expose only if direct access needed (besides Caddy)
      pass
    restart: unless-stopped
    networks:
      - media_network # Needs network to talk to Jellyfin, Radarr, Sonarr

networks:
  media_network:
    external: true
    name: media_network
