version: "3.8"
services:
  stash:
    image: nerethos/stash-jellyfin-ffmpeg
    container_name: stash
    environment:
      - PUID={{ user_puid }}
      - PGID={{ user_pgid }}
      - TZ=America/New_York
      - STASH_STASH=/data/ # Internal container path for stash data
    volumes:
      - "{{ base_data_dir }}/stash/config:/config" # Config yaml
      - "{{ base_data_dir }}/stash/generated:/data/generated" # Generated content previews etc.
      - "{{ base_data_dir }}/stash/metadata:/data/metadata" # Metadata DBs etc.
      - "{{ base_data_dir }}/stash/cache:/data/cache"
      - "{{ base_data_dir }}/stash/blobs:/data/blobs"
      - /home/alastor/Paul-McGann/Porn:/stash # If using blob storage
      # Mount your *actual* media libraries READ-ONLY here for Stash to scan
      # Example: - /path/to/your/real/media:/media:ro
    ports:
      # - "9999:9999" # Expose only if direct access needed (besides Caddy)
      pass
    # If Stash needs GPU for transcoding previews (less common), add:
    devices:
      - "nvidia.com/gpu=all"
    restart: unless-stopped
    networks:
      - media_network

networks:
  media_network:
    external: true
    name: media_network
