version: "3.8"
services:
  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID={{ user_puid }}
      - PGID={{ user_pgid }}
      - TZ=America/New_York
    volumes:
      - "{{ base_data_dir }}/prowlarr/config:/config"
    ports: pass
    # - "9696:9696" # Not needed, access via Caddy or Gluetun's network
    restart: unless-stopped
    network_mode: "service:gluetun" # Route traffic through Gluetun VPN
    depends_on:
      - gluetun
