version: "3.8"
services:
  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID={{ user_puid }}
      - PGID={{ user_pgid }}
      - TZ=America/New_York
      - AUTO_UPDATE=true # Optional: Enable internal updater
    volumes:
      - "{{ base_data_dir }}/jackett/config:/config"
      - "{{ base_data_dir }}/jackett/downloads:/downloads" # Blackhole directory
    ports: pass
    # - "9117:9117" # Not needed, access via Prowlarr/Gluetun network
    restart: unless-stopped
    network_mode: "service:gluetun" # Route traffic through Gluetun VPN
    depends_on:
      - gluetun
