version: "3.8"
services:
  sonarr:
    image: linuxserver/sonarr:latest # Use v3 or v4 image explicitly if needed: linuxserver/sonarr:preview
    container_name: sonarr
    environment:
      - PUID=2000
      - PGID=2000
      - TZ=America/New_York
    volumes:
      - /opt/podman-data/sonarr/config:/config
      - /path/to/your/downloads:/downloads # Example - MUST match download client path
      - /home/alastor/Sylvester-McCoy/Mine/Videos/Movies-4-The-Folders-Revenge:/Videos/Movies-4-The-Folders-Revenge
      - /home/alastor/Sylvester-McCoy/Mine/Videos/TV-4-The-Next-Generation:/Videos/TV-4-The-Next-Generation
      - /home/alastor/Sylvester-McCoy/Mine/Videos/UHD-Movies-A-New-Beginning:/Videos/UHD-Movies-A-New-Beginning
      - /home/alastor/Sylvester-McCoy/Mine/Videos/UHD-TV-Lucys-Tits:/Videos/UHD-TV-Lucys-Tits
      - /home/alastor/Paul-McGann/Videos/Movies\ 2\ -\ The\ Foldering:/Videos/Movies-2-The-Foldering
      - /home/alastor/Paul-McGann/Videos/Movies\ 3\ -\ The\ Final\ Folder:/Videos/Movies-3-The-Final-Folder
      - /home/alastor/Paul-McGann/Videos/TV\ 2\ -\ Electric\ Boogaloo:/Videos/TV-2-Electric-Boogaloo
      - /home/alastor/Paul-McGann/# (Optional) Global options
{
    email alastorripley@gmail.com # For ACME TLS certificates
    # acme_dns cloudflare your_api_token # If using DNS challenge
}

# --- Authelia Forward Auth Snippet (Placeholder - NEEDS WORK) ---
# See Authelia and Caddy documentation for proper setup!
(forward_auth) {
   forward_auth {
      uri http://authelia:9091/api/verify?rd=https%3A%2F%2F{host}{uri} # Use internal http
      copy_headers Authorization Remote-User Remote-Groups Remote-Name Remote-Email X-Forwarded-Proto X-Original-URL
      # IMPORTANT: Configure trusted_proxies in Authelia config to trust Caddy
   }
}

# --- Your Services ---

# Portainer
portainer.alastordeciditripley.com {
    import forward_auth # Uncomment to protect with Authelia (one_factor usually sufficient)
    reverse_proxy portainer:9000 # Proxy to internal HTTP port
}

# Gotify
gotify.alastordeciditripley.com {
    import forward_auth # Uncomment to protect with Authelia
    reverse_proxy gotify:80 # Proxy to internal container port (Host 8085 maps to Container 80)
}

# qBittorrent (Accessed via Gluetun network - Direct access often preferred)
# qbit.alastordeciditripley.com {
#    import forward_auth
#    reverse_proxy http://gluetun:8080
# }

# SABnzbd (Accessed via Gluetun network - Direct access often preferred)
# sab.alastordeciditripley.com {
#    # import forward_auth
#    reverse_proxy http://gluetun:8081
# }

# --- Existing Services (Add forward_auth as desired) ---

# Jellyfin Example
jellyfin.alastordeciditripley.com {
    import forward_auth # Uncomment to protect with Authelia
    reverse_proxy jellyfin:8096
    encode zstd gzip
}

# Sonarr Example
sonarr.alastordeciditripley.com {
    import forward_auth # Example: Protecting Sonarr
    reverse_proxy sonarr:8989
    encode zstd gzip
}

# Radarr Example
radarr.alastordeciditripley.com {
    import forward_auth # Example: Protecting Radarr
    reverse_proxy radarr:7878
    encode zstd gzip
}

# Lidarr Example
lidarr.alastordeciditripley.com {
    import forward_auth # Example: Protecting Lidarr
    reverse_proxy lidarr:8686
    encode zstd gzip
}

# Prowlarr Example
prowlarr.alastordeciditripley.com {
    import forward_auth # Example: Protecting Prowlarr
    reverse_proxy prowlarr:9696
    encode zstd gzip
}

# Homepage Example (Usually public)
home.alastordeciditripley.com {
    reverse_proxy homepage:3000
    encode zstd gzip
}

# Add other existing services similarly
stash.alastordeciditripley.com { 
    import forward_auth
    reverse_proxy stash:9999 
    }
# dozzle.alastordeciditripley.com { import forward_auth; reverse_proxy dozzle:8080 }
# kuma.alastordeciditripley.com { import forward_auth; reverse_proxy uptime-kuma:3001 }
request.alastordeciditripley.com { 
    import forward_auth
    reverse_proxy jellyseerr:5055 
    }
changedetection.alastordeciditripley.com {
    import forward_auth
    reverse_proxy changedetection:5000 
    }

# Authelia Portal (If accessed directly via subdomain - often not needed if using rd= query)
# auth.alastordeciditripley.com {
#    reverse_proxy authelia:9091
# }

    ports:
      # - "8989:8989" # Not needed, access via Caddy or Gluetun's network
      pass
    restart: unless-stopped
    network_mode: "service:gluetun" # Route traffic through Gluetun VPN
    depends_on:
      - gluetun
