version: "3.8"
services:
  lidarr:
    image: linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=2000
      - PGID=2000
      - TZ=America/New_York
    volumes:
      - /opt/podman-data/lidarr/config:/config
      - /path/to/your/downloads:/downloads # Example - MUST match download client path
      - /path/to/your/real/media/music:/music # Example
    ports:
      # - "8686:8686" # Not needed, access via Caddy or Gluetun's network
      pass
    restart: unless-stopped
    network_mode: "service:gluetun" # Route traffic through Gluetun VPN
    depends_on:
      - gluetun
