version: "3.8"
services:
  infra:
    image: some/infra-image:latest # CHANGE THIS to your actual image
    container_name: infra
    environment:
      - PUID={{ user_puid }}
      - PGID={{ user_pgid }}
      - TZ=America/New_York
      # - OTHER_ENV_VARS=needed_by_image
    volumes:
      - :{{ base_data_dir }}/infra/config:/config"" # Adjust path as needed
      # - "{{ base_data_dir }}/infra/data:/data" # Adjust path as needed
    ports: pass
    # - "XXXX:YYYY" # Expose ports if needed
    restart: unless-stopped
    networks:
      - media_network

networks:
  media_network:
    external: true
    name: media_network
