version: '3.8'
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      - PUID={{ user_puid }} # CHANGE 1000
      - PGID={{ user_pgid }} # CHANGE 1000
      # - HOMEPAGE_VAR_TZ=America/New_York # Set TZ via config file instead usually
    volumes:
      - "{{ base_data_dir }}/homepage/config:/app/config" # Mount your config directory
      # Mount podman socket (read-only) for container status widget
      - /run/user/1001/podman/podman.sock:/var/run/docker.sock:ro # CHANGE 1000
    ports: pass
    # - '3000:3000' # Expose only if direct access needed (besides Caddy)
    restart: unless-stopped
    networks:
      - media_network

networks:
  media_network:
    external: true
    name: media_network
